name: CI Pipeline

on:
  push:
    branches: [ main, playwright-tests]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build || true

      - name: Start the app
        run: nohup npm run start &

      - name: Wait for app
        run: |
          until curl -s http://localhost:3000/health; do
            echo "Waiting for the app..."
            sleep 5
          done

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Install k6
        run: |
          sudo apt update
          sudo apt install -y gnupg software-properties-common
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 33BD3F9A
          echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt update
          sudo apt install -y k6

      - name: Run k6 tests
        run: k6 run k6/performance.test.js